"""empty message

Revision ID: 0e46a157eab0
Revises: e4e211423930
Create Date: 2023-05-04 17:10:01.339437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e46a157eab0'
down_revision = 'e4e211423930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poolmbr_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.drop_column('poolmbr_status')

    # ### end Alembic commands ###
