"""empty message

Revision ID: 302cb108e94a
Revises: 4e704c68a998
Create Date: 2023-05-03 18:03:39.827103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302cb108e94a'
down_revision = '4e704c68a998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool_option', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_l4_pool_option_pool'), ['pool'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool_option', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_l4_pool_option_pool'), type_='unique')

    # ### end Alembic commands ###
