"""empty message

Revision ID: 4576d038416a
Revises: 6d5881f811d5
Create Date: 2023-05-04 16:17:09.006400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4576d038416a'
down_revision = '6d5881f811d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poolmbr_status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.drop_column('poolmbr_status')

    # ### end Alembic commands ###
