"""empty message

Revision ID: 47ad416bfca1
Revises: c953607cc15b
Create Date: 2023-05-02 18:08:44.674532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ad416bfca1'
down_revision = 'c953607cc15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
