"""empty message

Revision ID: 4e704c68a998
Revises: 47ad416bfca1
Create Date: 2023-05-03 18:01:52.168916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e704c68a998'
down_revision = '47ad416bfca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l4_pool_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_ttl', sa.Integer(), nullable=True),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_en', sa.String(length=20), nullable=False),
    sa.Column('pool_lbmod', sa.String(length=20), nullable=False),
    sa.Column('pool_alter', sa.String(length=20), nullable=False),
    sa.Column('pool_fallback', sa.String(length=20), nullable=False),
    sa.Column('pool_avail', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l4_pool_option'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l4_pool_option')
    # ### end Alembic commands ###
