"""empty message

Revision ID: 53da419ee7f3
Revises: c96537cde35f
Create Date: 2023-10-23 17:15:12.164595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53da419ee7f3'
down_revision = 'c96537cde35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nliveimgslb_pool', schema=None) as batch_op:
        batch_op.drop_constraint('uq_nliveimgslb_pool_pool', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nliveimgslb_pool', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_nliveimgslb_pool_pool', ['pool'])

    # ### end Alembic commands ###
