"""empty message

Revision ID: 6a940454efca
Revises: 4576d038416a
Create Date: 2023-05-04 16:25:30.690338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a940454efca'
down_revision = '4576d038416a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poolmbr_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.drop_column('poolmbr_status')

    # ### end Alembic commands ###
