"""empty message

Revision ID: 6b97f735550e
Revises: f329fe791764
Create Date: 2023-10-12 16:14:36.309389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b97f735550e'
down_revision = 'f329fe791764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afahvslb1_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb1_node'))
    )
    op.create_table('afahvslb1_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb1_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afahvslb1_pool_pool'))
    )
    op.create_table('afahvslb3_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb3_node'))
    )
    op.create_table('afahvslb3_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb3_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afahvslb3_pool_pool'))
    )
    op.create_table('afahvslb5_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb5_node'))
    )
    op.create_table('afahvslb5_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afahvslb5_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afahvslb5_pool_pool'))
    )
    op.create_table('kidcslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kidcslb_node'))
    )
    op.create_table('kidcslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kidcslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_kidcslb_pool_pool'))
    )
    op.create_table('nliveimgslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nliveimgslb_node'))
    )
    op.create_table('nliveimgslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nliveimgslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_nliveimgslb_pool_pool'))
    )
    op.create_table('nowlximgslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nowlximgslb_node'))
    )
    op.create_table('nowlximgslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nowlximgslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_nowlximgslb_pool_pool'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nowlximgslb_pool')
    op.drop_table('nowlximgslb_node')
    op.drop_table('nliveimgslb_pool')
    op.drop_table('nliveimgslb_node')
    op.drop_table('kidcslb_pool')
    op.drop_table('kidcslb_node')
    op.drop_table('afahvslb5_pool')
    op.drop_table('afahvslb5_node')
    op.drop_table('afahvslb3_pool')
    op.drop_table('afahvslb3_node')
    op.drop_table('afahvslb1_pool')
    op.drop_table('afahvslb1_node')
    # ### end Alembic commands ###
