"""empty message

Revision ID: 6d5881f811d5
Revises: 302cb108e94a
Create Date: 2023-05-04 14:05:44.203199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5881f811d5'
down_revision = '302cb108e94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l4_poolmbr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('poolmbr', sa.String(length=200), nullable=False),
    sa.Column('ratio', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l4_poolmbr'))
    )
    op.create_table('l4_poolmbr_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poolmbr', sa.String(length=200), nullable=False),
    sa.Column('poolmbr_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l4_poolmbr_option'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l4_poolmbr_option')
    op.drop_table('l4_poolmbr')
    # ### end Alembic commands ###
