"""empty message

Revision ID: 77650979f538
Revises: a4ee7d201e47
Create Date: 2023-10-10 14:02:29.469398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77650979f538'
down_revision = 'a4ee7d201e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afimgslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afimgslb_node'))
    )
    op.create_table('afimgslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afimgslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afimgslb_pool_pool'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afimgslb_pool')
    op.drop_table('afimgslb_node')
    # ### end Alembic commands ###
