"""empty message

Revision ID: a4ee7d201e47
Revises: 670fc3c63687
Create Date: 2023-10-05 14:28:36.639650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ee7d201e47'
down_revision = '670fc3c63687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afmainslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afmainslb_node'))
    )
    op.create_table('afmainslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afmainslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afmainslb_pool_pool'))
    )
    with op.batch_alter_table('l4_pool_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_1', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_l4_pool_option_pool_1'), ['pool_1'])

    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_port', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.drop_column('monitor_port')

    with op.batch_alter_table('l4_pool_option', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_l4_pool_option_pool_1'), type_='unique')
        batch_op.drop_column('pool_1')

    op.drop_table('afmainslb_pool')
    op.drop_table('afmainslb_node')
    # ### end Alembic commands ###
