"""empty message

Revision ID: c953607cc15b
Revises: de0a02ffe145
Create Date: 2023-04-28 15:14:52.576468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c953607cc15b'
down_revision = 'de0a02ffe145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.drop_constraint('uq_l4_pool_pool', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_l4_pool_pool', ['pool'])

    # ### end Alembic commands ###
