"""empty message

Revision ID: c96537cde35f
Revises: 6b97f735550e
Create Date: 2023-10-23 11:25:28.243769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96537cde35f'
down_revision = '6b97f735550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_refreshed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_last_refreshed'))
    )
    op.create_table('tr_s01_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s01_SW'))
    )
    op.create_table('tr_s02_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s02_SW'))
    )
    op.create_table('tr_s03_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s03_SW'))
    )
    op.create_table('tr_s04_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s04_SW'))
    )
    op.create_table('tr_s05_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s05_SW'))
    )
    op.create_table('tr_s06_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s06_SW'))
    )
    op.create_table('tr_s07_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s07_SW'))
    )
    op.create_table('tr_s08_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s08_SW'))
    )
    op.create_table('tr_s09_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s09_SW'))
    )
    op.create_table('tr_s10_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s10_SW'))
    )
    op.create_table('tr_s11_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s11_SW'))
    )
    op.create_table('tr_s12_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s12_SW'))
    )
    op.create_table('tr_s13_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s13_SW'))
    )
    op.create_table('tr_s14_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s14_SW'))
    )
    op.create_table('tr_s15_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s15_SW'))
    )
    op.create_table('tr_s16_SW',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Interface', sa.String(length=150), nullable=True),
    sa.Column('Host', sa.String(length=150), nullable=True),
    sa.Column('IP', sa.String(length=150), nullable=True),
    sa.Column('Mac', sa.String(length=150), nullable=True),
    sa.Column('Vlan', sa.String(length=150), nullable=True),
    sa.Column('Status', sa.String(length=150), nullable=True),
    sa.Column('Speed', sa.String(length=150), nullable=True),
    sa.Column('Type', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tr_s16_SW'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tr_s16_SW')
    op.drop_table('tr_s15_SW')
    op.drop_table('tr_s14_SW')
    op.drop_table('tr_s13_SW')
    op.drop_table('tr_s12_SW')
    op.drop_table('tr_s11_SW')
    op.drop_table('tr_s10_SW')
    op.drop_table('tr_s09_SW')
    op.drop_table('tr_s08_SW')
    op.drop_table('tr_s07_SW')
    op.drop_table('tr_s06_SW')
    op.drop_table('tr_s05_SW')
    op.drop_table('tr_s04_SW')
    op.drop_table('tr_s03_SW')
    op.drop_table('tr_s02_SW')
    op.drop_table('tr_s01_SW')
    op.drop_table('last_refreshed')
    # ### end Alembic commands ###
