"""empty message

Revision ID: e4e211423930
Revises: 6a940454efca
Create Date: 2023-05-04 17:08:49.033901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e211423930'
down_revision = '6a940454efca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poolmbr_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_poolmbr', schema=None) as batch_op:
        batch_op.drop_column('poolmbr_status')

    # ### end Alembic commands ###
