"""empty message

Revision ID: f085c0ac3c72
Revises: 39776bd70174
Create Date: 2023-04-28 14:57:40.596912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f085c0ac3c72'
down_revision = '39776bd70174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wideip', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('pool', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_l4_pool_pool'), ['pool'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('l4_pool', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_l4_pool_pool'), type_='unique')
        batch_op.drop_column('pool')
        batch_op.drop_column('wideip')

    # ### end Alembic commands ###
