"""empty message

Revision ID: f329fe791764
Revises: 77650979f538
Create Date: 2023-10-11 17:40:12.314799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f329fe791764'
down_revision = '77650979f538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afreecaslb_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('node', sa.String(length=200), nullable=False),
    sa.Column('node_port', sa.String(length=20), nullable=False),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afreecaslb_node'))
    )
    op.create_table('afreecaslb_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=200), nullable=False),
    sa.Column('pool_status', sa.String(length=20), nullable=False),
    sa.Column('pool_vip', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afreecaslb_pool')),
    sa.UniqueConstraint('pool', name=op.f('uq_afreecaslb_pool_pool'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afreecaslb_pool')
    op.drop_table('afreecaslb_node')
    # ### end Alembic commands ###
